### ISSUE TITLE
stypes.xsd - PhaseIDtype - NCTS5.1 typo

### ISSUE THREAD

**Issue by Krzysztof-Zielinski-C4T** [hmrc/transit-movements-validator#48]
There is an additional white space prefix for phaseIDtype with option NCTS5.1.
The option with NCTS5.0 is valid.
https://github.com/hmrc/transit-movements-validator/blob/932e96178fe5afbc067c4c599c2e2226fe6e98d8/conf/xsd/stypes.xsd#L4388C30-L4388C32

**Comment by drnaylor-oc** [comment]
This has been updated in the XSDs now.
